socialnetwork/urls.py
from django.urls import path
from socialnetwork import views


urlpatterns = [
    path('', views.global_action, name='home'),
    path('login', views.login_action, name='login'),
    path('register', views.register_action, name='register'),
    path('logout', views.logout_action, name='logout'),
    path('global', views.global_action, name='global'),
    path('follower', views.follower_action, name='follower'),
    path('profile', views.user_profile_action, name='profile'),
    path('other-profile/<int:id>', views.follower_profile_action, name='other-profile'),
    path('photo/<int:id>', views.get_user_photo, name="photo"),
    path('get-global', views.get_global, name='get-global'),
    path('get-follower', views.get_follower, name='get-follower'),
    path('add-comment', views.add_comment, name='add-comment'),
]

webapps/urls.py
from django.contrib import admin
from django.urls import path, include
from socialnetwork import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.global_action, name='home'),
    path('socialnetwork/', include('socialnetwork.urls'))
]

socialnetwork/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# ------------------------------------------------------------------------------------------------------------------------------#
# --- USER MODELS --- #
# ------------------------------------------------------------------------------------------------------------------------------#
class Profile(models.Model):
    #############################################################################################################################
    # @brief      :       Creates django form class for user profile
    #############################################################################################################################
    profile_user = models.ForeignKey(User, on_delete=models.PROTECT)
    user_bio = models.CharField(max_length=200, default=" ")
    user_picture = models.FileField(blank=True)
    picture_type = models.CharField(max_length=200, default="None")
    followers = models.ManyToManyField(User, blank=True, related_name="user_following")

# ------------------------------------------------------------------------------------------------------------------------------#
# --- CONTENT MODELS --- #
# ------------------------------------------------------------------------------------------------------------------------------#
class Post(models.Model):
    #############################################################################################################################
    # @brief      :       Creates django form class for blog post
    #############################################################################################################################
    post_input_text = models.CharField(max_length=200)
    profile = models.ForeignKey(User, on_delete=models.PROTECT, related_name="post_creators")
    date_time = models.DateTimeField()




class Comment(models.Model):
    #############################################################################################################################
    # @brief      :       Creates django form class for comment post
    #############################################################################################################################
    comment_input_text = models.CharField(max_length=200)
    profile = models.ForeignKey(User, on_delete=models.PROTECT, related_name="comment_creators")
    date_time = models.DateTimeField()
    post = models.ForeignKey(Post, on_delete=models.PROTECT, related_name="comment_post")

socialnetwork/forms.py
from django import forms

from django.contrib.auth.models import User
from django.contrib.auth import authenticate

from socialnetwork.models import Post, Comment, Profile

# ------------------------------------------------------------------------------------------------------------------------------#
# --- LOGIN FORMS --- #
# ------------------------------------------------------------------------------------------------------------------------------#
class LoginForm(forms.Form):
    #############################################################################################################################
    # @brief      :       Creates django form class for user logins
    #############################################################################################################################
    username = forms.CharField(max_length = 20)                                         #< Unique Username Input for Site
    password = forms.CharField(max_length = 200, widget=forms.PasswordInput())          #< Unique User Password

    # -- CLASS METHODS -- #
    """
        @brief      :       Custom form validation that applies to multiple fields
        @note       :       Overrides the forms.Form.clean function
    """
    def clean(self):
        # Calls our parent (forms.Form) .clean function, gets a dictionary
        # of cleaned data as a result
        cleaned_data = super().clean()

        # Confirm the Password is correct for given username
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if not user:
            raise forms.ValidationError("Invalid Username/Password")

        return cleaned_data



# ------------------------------------------------------------------------------------------------------------------------------#
# --- REGISTRATION FORMS --- #
# ------------------------------------------------------------------------------------------------------------------------------#
class RegisterForm(forms.Form):  
    #############################################################################################################################
    # @brief      :       Creates django form class for user account registration
    #############################################################################################################################
    username = forms.CharField(max_length = 20)                                             #< Unique Username Input for Site
    password = forms.CharField(max_length = 200, widget=forms.PasswordInput())              #< Unique User Password
    confirm_password =  forms.CharField(max_length = 200, widget=forms.PasswordInput())     #< Password Confirmation Input
    email = forms.CharField(max_length = 50, widget= forms.EmailInput())                    #< Email Linked to User Account
    first_name = forms.CharField(max_length = 20)                                           #< User's First Name
    last_name = forms.CharField(max_length = 20)                                            #< User's Last Name 


    # -- CLASS METHODS -- #
    """
        @brief      :       Custom form validation that applies to multiple fields
        @note       :       Overrides the forms.Form.clean function
    """
    def clean(self):
        # Calls our parent (forms.Form) .clean function, gets a dictionary
        # of cleaned data as a result
        cleaned_data = super().clean()

        # Confirm the Password fields match
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if (password and confirm_password) and (password != confirm_password):
            raise forms.ValidationError("Passwords did not Match")

        return cleaned_data

# ------------------------------------------------------------------------------------------------------------------------------#
# --- PROFILE FORMS --- #
# ------------------------------------------------------------------------------------------------------------------------------#
class UserProfileForm(forms.Form):
    #############################################################################################################################
    # @brief      :       Creates django form class for user to edit their profile page
    #############################################################################################################################
    bio_input_text = forms.CharField(widget=forms.Textarea)

class EditProfileForm(forms.ModelForm):
    #############################################################################################################################
    # @brief      :       Creates django form class for user to edit their profile page
    #############################################################################################################################
    class Meta:
        model = Profile
        exclude = (
            'profile_user',
            'followers',
            'picture_type'
        )
        widgets = {
            'user_bio': forms.Textarea(attrs={'id': 'id_bio_input_text',}),
            'user_picture': forms.ClearableFileInput(attrs={'id': 'id_profile_picture', 'class' : 'btn btn-light mx-2'}),
        }


# ------------------------------------------------------------------------------------------------------------------------------#
# --- CONTENT FORMS --- #
# ------------------------------------------------------------------------------------------------------------------------------#
class CreatePostForm(forms.ModelForm):
    #############################################################################################################################
    # @brief      :       Creates django form class to create post from post model
    #############################################################################################################################
    class Meta:
        model = Post
        exclude = (
            'profile',
            'date_time'
        )
        widgets = {
            'date_time': forms.HiddenInput(),
            'post_input_text': forms.TextInput(attrs={'id': 'id_post_input_text','class': 'form-control px-2'}),
        }


class CreateCommentForm(forms.ModelForm):
    #############################################################################################################################
    # @brief      :       Creates django form class to create comment from post comment
    #############################################################################################################################
    class Meta:
        model = Comment 
        exclude = (
            'profile',
            'date_time'
        )
        widgets = {
            'date_time': forms.HiddenInput(),
            'input_text': forms.Textarea()
        }

socialnetwork/templates/socialnetwork/base.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        {% load static %}
        <script src="{% static 'socialnetwork/socialnetwork.js' %}"></script>

        <!-- Add Boostrap Dependencies-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>

        <!-- Add Custom Styling and JS -->
        <link href="{% static 'socialnetwork/base.css' %}" rel="stylesheet" type="text/css">
        
        <!-- Load JS Script & JQuery-->
        <script src="https://code.jquery.com/jquery-3.6.3.min.js"
                integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>

        <title> {% block title %} Social Network {% endblock %}</title>
    </head>
    <body >
        <div class="container-fluid align-items-stretch justify-content-between" id="id_base_body_container">
            <div class="bg-light row" id="id_header_div">
                {% block navigation-bar %}
                {% endblock %}
            </div>            
                
                    
            <div class="row d-flex justify-content-between align-items-stretch p-0" id="id_content_div">
                {% if message %}
                    <div class="container-fluid" id="id_base_message_row">
                        <div class="message">
                            {{message}}
                        </div>
                    </div>
                {% endif %}

                {% block content %}
                {% endblock %}
            </div>
                    
        </div>

    </body>

</html>

socialnetwork/templates/socialnetwork/follower.html
{% extends "socialnetwork/navbar.html" %}

{% block content %}
<div class="d-flex flex-column justify-content-start align-items-stretch flex-nowrap bg-dark"
    id="id_follower_page_content">

    <!-- PAGE HEADER -->
    <div class="bg-primary d-flex flex-column justify-content-around align-items-center py-2 my-2"
        id="id_follower_header_row">
        <!-- PAGE TITLE-->
        <div class="row justify-content-center align-items-center">
            <span class="follower-page-name" id="id_page_name">{{page_name}}</span>
        </div>

    </div>

    <!-- PAGE CONTENT -->
    <div id="id_follower_content_div" class="container-fluid flex-grow-1 bg-primary justify-content-center align-items-center py-2">

    

    </div>
    <script>
        // Call as soon as document has loaded to display list  
        window.onload = loadFollowerPost;
        window.setInterval(loadFollowerPost, 5000);



    </script>

</div>

{% endblock %}

socialnetwork/templates/socialnetwork/follower_profile.html
{% extends "socialnetwork/profile.html" %}
{% load static %}

{% block profile-page %}
<!-- USER BIO -->
<div class="card justify-content-center align-items-center my-2 p-2" id="id_profile_edit_div">
    <form class="d-flex flex-column justify-content-center align-items-center" method="post" action="{% url 'other-profile' profile.id %}">
            <textarea readonly class="form-control-plain-text py-2 my-2" id="id_user_bio"> {{profile.user_bio}}</textarea>    
            <button type="submit" class="btn btn-light py-2 my-2" id="id_{{button_text}}">{{button_text}}</button>
            {% csrf_token %}
    </form>
</div>

<!-- FOLLOWER LIST -->

{% endblock %}

socialnetwork/templates/socialnetwork/global.html
{% extends "socialnetwork/navbar.html" %}
{% load static %}

{% block content %}

<div class="d-flex flex-column justify-content-start align-items-stretch flex-nowrap bg-dark"
    id="id_global_page_content">

    <!-- PAGE HEADER -->
    <div class="bg-primary d-flex flex-column justify-content-around align-items-center py-2 my-2" id="id_global_header_row">
        <!-- PAGE TITLE-->
        <div class="row justify-content-center align-items-center">
            <span class="global-page-name" id="id_page_name">{{page_name}}</span>
        </div>

        <!-- CONSTRUCT POST -->
        <div class="bg-secondary row justify-content-center align-items-center" id="id_global_post_div">
            <form class="bg-white d-flex flex-row justify-content-center align-items-center" id="id_post_form" method="post" action="{% url 'global' %}">
                <div class="bg-primary flex-fill flex-nowrap input-group d-flex flex-row justify-content-around align-items-center text-center" id="id_post_container">
                    <label class="input-group-text text-center px-2" for="id_post_input_text" id="id_post_input_text_label">New Post:</label>
                    {{post_form.post_input_text}}
                    <button type="submit" class="btn btn-light px-2" id="id_post_button">Submit</button>
                </div>
                {% csrf_token %}
            </form>
        </div>

    </div>

    <!-- PAGE CONTENT -->
    <div class = "container-fluid flex-grow-1 bg-primary justify-content-center align-items-center py-2" id="id_global_content_div">



    </div>
    <script>
        // Call as soon as document has loaded to display list  
        window.onload = loadGlobalPost;
        window.setInterval(loadGlobalPost, 5000);



    </script>

</div>

{% endblock %}

socialnetwork/templates/socialnetwork/login.html
{% extends "socialnetwork/login_layout.html" %}


{% block content-form%}

<!-- Login Form -->
<form class="bg-white" method="post" action="{% url 'login' %}" id="id_login_form">
    {% if form.non_field_errors %}
        <div class="alert alert-error non-field-errors px-0 text-muted">
            {% for error in form.non_field_errors %}
                <span class="errorlist">{{error}}</span>
            {% endfor %}
        </div>
    {% endif %}
    
    <div class="form-group justify-content-center align-items-center py-1 px-0" id="id_login_username_container">
        <label class="form-label m-0" for='id_username'> Username:</label>
        {{form.username}}
    </div>

    <div class="bg-primary form-group justify-content-center align-items-center py-1 px-0" id="id_login_password_container">
        <label class="form-label m-0" for='id_password' > Password:</label>
        {{form.password}}
    </div>

                
    <div class="bg-primary d-flex bg-primary text-center justify-content-center align-items-center align-self-stretch py-4 px-0" id="id_login_button_container">
        <button type="submit form_button" class="btn btn-dark py-2" id="id_login_button"> Submit </button>
    </div>


    {% csrf_token %}

</form>

{% endblock %}

socialnetwork/templates/socialnetwork/login_layout.html
{% extends "socialnetwork/navbar.html" %}

{% block content%}
<div class="d-flex flex-row justify-content-between align-items-stretch flex-nowrap p-0 bg-primary"
    id="id_login_page_content">
    <div class="container d-flex" id="id_login_graphic_container">

    </div>

    <!-- Content -->
    <div class=" bg-white d-flex flex-column justify-content-center align-items-stretch flex-nowrap p-5"
        id="id_login_text_container">
        <div class="bg-primary d-flex justify-content-center align-items-center py-2 my-2" id="id_login_header_row">
            <span id="id_page_name">{{page_name}}</span>
        </div>

        <div class="d-flex bg-dark justify-content-center align-items-center p-2" id="id_login_content_row">
            {% block content-form %}
            {% endblock %}
        </div>

    </div>
</div>

{% endblock %}

socialnetwork/templates/socialnetwork/navbar.html
{% extends "socialnetwork/base.html" %}

{% block navigation-bar %}
<nav class= "navbar bg-light">
    <div class="container-fluid">
        <!-- Site Header -->
        <span class="navbar-brand" id="id_site_name">Social Network</span>

        <!-- Navbar Links -->
        <div class="navbar-nav d-flex flex-column align-items-end">
        <!-- If Logged in Show link to Profile Page -->
            {% if user.is_authenticated and page_name != "Login" and pagename != "Register"%}
                <span><a class="nav-link px-2" id='id_nav_profile' href='{% url 'profile' %}''>{{user.first_name}} {{user.last_name}}</a></span>
            {% else %}
                <span>&nbsp;</span>
            {% endif %}

            <ul class="navbar-nav d-flex flex-row justify-content-end, align-items-center">
                {% for item in navigation_links %}
                    <li><a class='{{item.class_name}}' id='{{item.id}}' href='{% url item.link %}''>{{item.inner_text}}</a></li>
                {% endfor %}
            </ul>
        </div>
      
    </div>
</nav>
{% endblock %}

socialnetwork/templates/socialnetwork/post.html
{% extends "socialnetwork/navbar.html" %}

socialnetwork/templates/socialnetwork/profile.html
{% extends "socialnetwork/navbar.html" %}

{% block content %}
{% load static %}


<div class="d-flex flex-column justify-content-start align-items-stretch flex-nowrap bg-dark"
    id="id_profile_content">

    <!-- PAGE HEADER -->
    <div class="bg-primary d-flex flex-column justify-content-around align-items-center py-2"
        id="id_profile_header_row">
        <!-- PAGE TITLE-->
        <div class="row justify-content-center align-items-center mb-2">
            <span class="profile-page-name" id="id_page_name">{{page_name}} {{profile.profile_user.first_name}} {{profile.profile_user.last_name}}</span>
        </div>

        <!-- PROFILE IMAGE-->
        <div class="row justify-content-center align-items-center bg-white my-4" id="id_profile_image_div">
            {% if profile.picture_type == 'None' %}
                <img src="{% static 'socialnetwork/profile_image.png' %}" id="id_user_picture">
            {% else %}
                <img src="{% url 'photo' profile.id %}" id="id_user_picture">
            {% endif %}
        </div>

    </div>

    <!-- PAGE CONTENT -->
    <div class="container-fluid  bg-primary justify-content-center align-items-center py-2">
        <!-- LOAD USER PROFILE OR FOLLOWER PROFILE -->
        {% block profile-page  %}
        {% endblock %}
    </div>

    <!-- FOLLOWER LIST -->
    <div class="card flex-grow-1 my-2 p-2" id="id_follower_list_div">
    
        <div class="card-body">
            <h5 class="card-title mb-2">Following:</h5>
            <ul class="list-group list-group-light">
                {% for follower in followers %}
                    <li class="list-group-item">
                        <a class="text" id="id_profile_link_{{follower.profile_user.username}}" href="{% url 'other-profile' follower.id %}">{{follower.profile_user.first_name}} {{follower.profile_user.last_name}}</a>
                    </li> 
                {% endfor %}
            </ul>
        </div>
    
    </div>

</div>
{% endblock %}

socialnetwork/templates/socialnetwork/register.html
{% extends "socialnetwork/login_layout.html" %}


{% block content-form%}

<!-- Register Form -->
<form class="bg-white" method="post" action="{% url 'register' %}" id="id_register_form">
    {% if form.non_field_errors %}
        <div class="alert alert-error non-field-errors px-0 text-muted">
            {% for error in form.non_field_errors %}
            <span class="errorlist">{{error}}</span>
            {% endfor %}
        </div>
    {% endif %}
    
    <div class="form-group justify-content-center align-items-center py-1 px-0" id="id_register_username_container">
        <label class="form-label m-0" for='id_username'>Username:</label>
        {{form.username}}
    </div>

    <div class="bg-primary form-group justify-content-center align-items-center py-1 px-0"
        id="id_register_password_container">
        <label class="form-label m-0" for='id_password'>Password:</label>
        {{form.password}}
    </div>

    <div class="bg-white form-group justify-content-center align-items-center py-1 px-0" id="id_register_confirm_password_container">
        <label class="form-label bg-secondary m-0" for='id_confirm_password'>Confirm Password:</label>
        {{form.confirm_password}}
    </div>

    <div class="bg-primary form-group justify-content-center align-items-center py-1 px-0"
        id="id_register_email_container">
        <label class="form-label m-0" for='id_email'>Email:</label>
        {{form.email}}
        {% for error in form.email.errors %}
            <span class="text-muted px-0">{{ error }}</span>
        {% endfor %}
    </div>

    <div class="bg-primary form-group justify-content-center align-items-center py-1 px-0"
        id="id_register_first_name_container">
        <label class="form-label m-0" for='id_first_name'>First Name:</label>
        {{form.first_name}}
    </div>

    <div class="bg-white form-group justify-content-center align-items-center py-1 px-0"
        id="id_register_last_name_container">
        <label class="form-label m-0" for='id_last_name'>Last Name:</label>
        {{form.last_name}}
    </div>

    <div class="bg-primary d-flex bg-primary text-center justify-content-center align-items-center align-self-stretch py-4 px-0"
        id="id_register_button_container">
        <button type="submit form_button" class="btn btn-dark py-2" id="id_register_button"> Submit </button>
    </div>

    {% csrf_token %}

</form>
{% endblock %}

socialnetwork/templates/socialnetwork/user_profile.html
{% extends "socialnetwork/profile.html" %}
{% load static %}

{% block profile-page %}
<!-- EDITABLE USER BIO -->
<div class="card justify-content-center align-items-center my-2 p-2" id="id_profile_edit_div">
    <form enctype="multipart/form-data" class="d-flex flex-column justify-content-center align-items-center" method="post" action="{% url 'profile'%}">
        <div class="input-group justify-content-center align-items-center py-2 my-2" id="id_bio_edit_div">
            {{form.user_bio}}
        </div>

        <div class="d-flex flex-row bg-primary justify-content-center align-items-center my-2" id="id_pic_edit_div">
            <span class="mx-2">Profile Picture</span>
            {{form.user_picture}}
        </div>

        <div class="d-flex py-2 my-2">
            <button type="submit" class="btn btn-light" id="id_update_profile_button">Submit</button>
        </div>

        {% csrf_token %}

    </form>
</div>


{% endblock %}